### ISSUE TITLE
doesnt work despite being installed

### ISSUE THREAD

**Issue by 2blackbar** [vijishmadhavan/UnpromptedControl#1]
Would you care to post step by step for auto11 ? So its supposed to work without any prompts? thats not a good idea to remove stuff when theres no prompt and you mask stuff.
Is it a scripr? what cfg, whad denoise, what maximum res, what sampler,inpaint only masked or whole picuture, the explanation is pretty vague/not nonexistant, not sure where from now on, it just doesnt work, behaves like normal and inpaints random stuff in same place without prompt.

**Comment by vijishmadhavan** [comment]
I have a colab link, where you can try it.

**Comment by 2blackbar** [comment]
works well there but in auto11 it doesnt, maybe its just some rumor that it works in auto11
![image](https://user-images.githubusercontent.com/33694664/235223200-c59be4b3-4544-4ef5-a5de-838636f01952.png)
