### ISSUE TITLE
Video guide?

### ISSUE THREAD

**Issue by ffdown** [vijishmadhavan/UnpromptedControl#2]
How use this??

**Comment by 2blackbar** [comment]
I found using inpaint model and denose at 1, typing in prompt "empty"  or depending on what you want to inpaint, works just as good as this so you dont really ned this script, sd is pretty amazing at inpainting in only masked mode, it can mimic the style  of the photo, recreate windows, buildings, even cartoon art sticking to the style

**Comment by vijishmadhavan** [comment]
Okay
